version: 2
jobs:
  build_ccl_amd64:
    docker:
      - image: "love5an/dotnet-core-sdk-common-lisp:2.2-ccl-latest-stretch"

    working_directory: ~/quicklisp/local-projects/bike

    steps:

      - checkout

      - run:
          name: Run tests
          command: cat tests.lisp | ccl64 -Q -b

  build_sbcl_amd64:
    docker:
      - image: "love5an/dotnet-core-sdk-common-lisp:2.2-sbcl-latest-stretch"

    working_directory: ~/quicklisp/local-projects/bike

    steps:

      - checkout

      - run:
          name: Run tests
          command: cat tests.lisp | sbcl --disable-debugger --noprint

workflows:
  version: 2

  tests:
    jobs:
      - build_ccl_amd64
      - build_sbcl_amd64
