version: 2
jobs:
  build_2_2_ccl_amd64:
    docker:
      - image: "love5an/dotnet-core-sdk-common-lisp:2.2-ccl-latest-stretch"
    working_directory: ~/quicklisp/local-projects/bike
    steps:
      - checkout
      - run:
          name: Run tests
          command: cat tests.lisp | ccl64 -Q -b

  build_3_0_ccl_amd64:
    docker:
      - image: "love5an/dotnet-core-sdk-common-lisp:3.0-ccl-latest-bionic"
    working_directory: ~/quicklisp/local-projects/bike
    steps:
      - checkout
      - run:
          name: Run tests
          command: cat tests.lisp | ccl64 -Q -b

  build_2_2_sbcl_amd64:
    docker:
      - image: "love5an/dotnet-core-sdk-common-lisp:2.2-sbcl-latest-stretch"
    working_directory: ~/quicklisp/local-projects/bike
    steps:
      - checkout
      - run:
          name: Run tests
          command: cat tests.lisp | sbcl --disable-debugger --noprint

  build_3_0_sbcl_amd64:
    docker:
      - image: "love5an/dotnet-core-sdk-common-lisp:3.0-sbcl-latest-bionic"
    working_directory: ~/quicklisp/local-projects/bike
    steps:
      - checkout
      - run:
          name: Run tests
          command: cat tests.lisp | sbcl --disable-debugger --noprint

workflows:
  version: 2

  tests:
    jobs:
      - build_2_2_ccl_amd64
      - build_3_0_ccl_amd64
      - build_2_2_sbcl_amd64
      - build_3_0_sbcl_amd64
